  const sentences = [
    "Now we bussin!",
    "I verified the Golden let's go!",
    "Are you ready for some badassery?",
    "GG on Acheron!",
    "2.3 soon!",
    "Duel asymetrico, preparate!",
    "Swag route, let's go!",
    "Dora no care!",
    "I love gd cologne!",
    "3 2 1 Geometry Dash!",
    "Bloodlust!",
    "Fire in the hole!",
    "SHIVER ME TIMBERS!",
    "All GD players put ya hands up!",
    "Does this look possible to you?",
    "Also try Hollow Knight: Silksong!",
    "Also try Ori and the WIll of the Wisps!",
    "Pro tip: Jump!",
    "Now with ducks!",
    "CBF detected, loser!",
    "Remember that day!",
    "Experiment!",
    "My hope will never die!",
    "Act like I got cheat codes!",
    "I like this part :)",
    "I spy with my little eye!",
    "To the recent tab!",
    "You need to rest!",
    "She's in love with the concept!",
    "It's so unsightreadable!",
    "This is the attempt!",
    "Bwomp!",
    "Get ready for a lot of fun!",
    "Only in Ohio dawg!",
    "You've been trolled!",
    "Never kill yourself!",
    "Don't try Roblox!",
    "Next cab soon!",
    "Now with more bugs!",
    "Check steam!",
    "We make art!",
  ];

  const randomSentence = sentences[Math.floor(Math.random() * sentences.length)];

  document.getElementById("sentence").textContent = randomSentence;
