// Randomizer
  const sentences = [
    "Now we bussin!",
    "I verified the Golden let's go!",
    "Are you ready for some badassery?",
    "GG on Acheron!",
    "Duel asymetrico, preparate!",
    "Swag route, let's go!",
    "Dora no care!",
    "I love gd cologne!",
    "3 2 1 Geometry Dash!",
    "Bloodlust!",
    "Fire in the hole!",
    "SHIVER ME TIMBERS!",
    "All GD players put ya hands up!",
    "Does this look possible to you?",
    "Also try Hollow Knight: Silksong!",
    "Also try Ori and the Will of the Wisps!",
    "Pro tip: Jump!",
    "Get back on Grief!",
    "Now with more memes!",
    "Now with ducks!",
    "CBF detected, loser!",
    "Remember that day!",
    "Experiment!",
    "My hope will never die!",
    "Act like I got cheat codes!",
    "I like this part :)",
    "I spy with my little eye!",
    "To the recent tab!",
    "You need to rest!",
    "She's in love with the concept!",
    "It's so unsightreadable!",
    "This is the attempt!",
    "Bwomp!",
    "Get ready for a lot of fun!",
    "Only in Ohio dawg!",
    "You've been trolled!",
    "Never kill yourself!",
    "Don't try Roblox!",
    "Next cab soon!",
    "Now with more bugs!",
    "Check steam!",
    "We make art!",
    "Skibidi dop dop yes yes",
    "1 John 5:19!",
    "RubyRubyRubyRuby!",
    "February 11th!",
    "You are all banned!",
    "This is a rare message. Or is it?",
    "You actually found this?",
    "Add me on Steam!",
    "Hello everybody, my name is Welcome!",
    "He looks so Portuguese!",
    "Yeah!",
    "Published by Based Department!",
    "You might be using Mobile Data right now!",
    "Masterful gambit, sir!",
    "To the Gambling Dimension!",
    "Shaw!",
    "Poshanka!",
  ];

  const randomSentence = sentences[Math.floor(Math.random() * sentences.length)];

  document.getElementById("splash").textContent = randomSentence;
